name: Validity checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 10.x

      - name: Run syntax checks against redirections.js
        run: node -c redirections.js

  validity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1.2.0
        with:
          python-version: 3.7

      - name: Check validity of the links
        run: |
          python validity_checks.py